//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.24 at 03:52:09 PM CEST 
//


package bezbednost.poslovna.xml.ws.faktura;

import java.math.BigDecimal;
import java.text.DecimalFormat;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PodaciRobaIUsluga complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PodaciRobaIUsluga">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="VrednostRobe" type="{http://xml.poslovna.bezbednost/ws/Faktura}VrednostRobe"/>
 *         &lt;element name="VrednostUsluga" type="{http://xml.poslovna.bezbednost/ws/Faktura}VrednostUsluga"/>
 *         &lt;element name="UkupnoRobaIUsluga" type="{http://xml.poslovna.bezbednost/ws/Faktura}UkupnoRobaIUsluga"/>
 *         &lt;element name="UkupanRabat" type="{http://xml.poslovna.bezbednost/ws/Faktura}UkupanRabat"/>
 *         &lt;element name="UkupanPorez" type="{http://xml.poslovna.bezbednost/ws/Faktura}UkupanPorez"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PodaciRobaIUsluga", propOrder = {
    "vrednostRobe",
    "vrednostUsluga",
    "ukupnoRobaIUsluga",
    "ukupanRabat",
    "ukupanPorez"
})
public class PodaciRobaIUsluga {

    @XmlElement(name = "VrednostRobe", required = true)
    protected BigDecimal vrednostRobe;
    @XmlElement(name = "VrednostUsluga", required = true)
    protected BigDecimal vrednostUsluga;
    @XmlElement(name = "UkupnoRobaIUsluga", required = true)
    protected BigDecimal ukupnoRobaIUsluga;
    @XmlElement(name = "UkupanRabat", required = true)
    protected BigDecimal ukupanRabat;
    @XmlElement(name = "UkupanPorez", required = true)
    protected BigDecimal ukupanPorez;

    /**
     * Gets the value of the vrednostRobe property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVrednostRobe() {
        return vrednostRobe;
    }

    /**
     * Sets the value of the vrednostRobe property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVrednostRobe(BigDecimal value) {
        this.vrednostRobe = value;
    }

    /**
     * Gets the value of the vrednostUsluga property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getVrednostUsluga() {
        return vrednostUsluga;
    }

    /**
     * Sets the value of the vrednostUsluga property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setVrednostUsluga(BigDecimal value) {
        this.vrednostUsluga = value;
    }

    /**
     * Gets the value of the ukupnoRobaIUsluga property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getUkupnoRobaIUsluga() {
        return ukupnoRobaIUsluga;
    }

    /**
     * Sets the value of the ukupnoRobaIUsluga property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setUkupnoRobaIUsluga(BigDecimal value) {
        this.ukupnoRobaIUsluga = value;
    }

    /**
     * Gets the value of the ukupanRabat property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getUkupanRabat() {
        return ukupanRabat;
    }

    /**
     * Sets the value of the ukupanRabat property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setUkupanRabat(BigDecimal value) {
        this.ukupanRabat = value;
    }

    /**
     * Gets the value of the ukupanPorez property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getUkupanPorez() {
        return ukupanPorez;
    }

    /**
     * Sets the value of the ukupanPorez property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setUkupanPorez(BigDecimal value) {
        this.ukupanPorez = value;
    }

	@Override
	public String toString() {
		return "PodaciRobaIUsluga [vrednostRobe=" + new DecimalFormat("#0.##").format(vrednostRobe) + ", vrednostUsluga=" + new DecimalFormat("#0.##").format(vrednostUsluga) 
				+ ", ukupnoRobaIUsluga=" + new DecimalFormat("#0.##").format(ukupnoRobaIUsluga)  + ", ukupanRabat=" + new DecimalFormat("#0.##").format(ukupanRabat) + ", ukupanPorez="
				+ new DecimalFormat("#0.##").format(ukupanPorez) + "]";
	}
}
