//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.27 at 10:41:51 PM CEST 
//


package bezbednost.poslovna.xml.ws.faktura;

import java.math.BigDecimal;
import java.text.DecimalFormat;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for PodaciOUplati complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PodaciOUplati">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OznakaValute" type="{http://xml.poslovna.bezbednost/ws/Faktura}OznakaValute"/>
 *         &lt;element name="IznosZaUplatu" type="{http://xml.poslovna.bezbednost/ws/Faktura}IznosZaUplatu"/>
 *         &lt;element name="Uplata_na_racun" type="{http://xml.poslovna.bezbednost/ws/Faktura}TBrojRacuna"/>
 *         &lt;element name="Datum_valute" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PodaciOUplati", propOrder = {
    "oznakaValute",
    "iznosZaUplatu",
    "uplataNaRacun",
    "datumValute"
})
public class PodaciOUplati {

    @XmlElement(name = "OznakaValute", required = true)
    protected String oznakaValute;
    @XmlElement(name = "IznosZaUplatu", required = true)
    protected BigDecimal iznosZaUplatu;
    @XmlElement(name = "Uplata_na_racun", required = true, defaultValue = "000-0000000000000-00")
    protected String uplataNaRacun;
    @XmlElement(name = "Datum_valute", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datumValute;

    /**
     * Gets the value of the oznakaValute property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOznakaValute() {
        return oznakaValute;
    }

    /**
     * Sets the value of the oznakaValute property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOznakaValute(String value) {
        this.oznakaValute = value;
    }

    /**
     * Gets the value of the iznosZaUplatu property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIznosZaUplatu() {
        return iznosZaUplatu;
    }

    /**
     * Sets the value of the iznosZaUplatu property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIznosZaUplatu(BigDecimal value) {
        this.iznosZaUplatu = value;
    }

    /**
     * Gets the value of the uplataNaRacun property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUplataNaRacun() {
        return uplataNaRacun;
    }

    /**
     * Sets the value of the uplataNaRacun property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUplataNaRacun(String value) {
        this.uplataNaRacun = value;
    }

    /**
     * Gets the value of the datumValute property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatumValute() {
        return datumValute;
    }

    /**
     * Sets the value of the datumValute property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatumValute(XMLGregorianCalendar value) {
        this.datumValute = value;
    }
    
    @Override
	public String toString() {
		return "PodaciOUplati [oznakaValute=" + oznakaValute + ", iznosZaUplatu=" + new DecimalFormat("#0.##").format(iznosZaUplatu) + ", uplataNaRacun="
				+ uplataNaRacun + ", datumValute=" + datumValute.toString() + "]";
	}

}
