//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.24 at 03:52:09 PM CEST 
//


package bezbednost.poslovna.xml.ws.faktura;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Zaglavlje complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Zaglavlje">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IDPoruke" type="{http://xml.poslovna.bezbednost/ws/Faktura}IDPoruke"/>
 *         &lt;element name="PodaciODobavljacu" type="{http://xml.poslovna.bezbednost/ws/Faktura}TPravnoLice"/>
 *         &lt;element name="PodaciOKupcu" type="{http://xml.poslovna.bezbednost/ws/Faktura}PodaciOKupcu"/>
 *         &lt;element name="PodaciRobaIUsluga" type="{http://xml.poslovna.bezbednost/ws/Faktura}PodaciRobaIUsluga"/>
 *         &lt;element name="PodaciOUplati" type="{http://xml.poslovna.bezbednost/ws/Faktura}PodaciOUplati"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Zaglavlje", propOrder = {
    "idPoruke",
    "podaciODobavljacu",
    "podaciOKupcu",
    "podaciRobaIUsluga",
    "podaciOUplati"
})
public class Zaglavlje {

    @XmlElement(name = "IDPoruke", required = true)
    protected String idPoruke;
    @XmlElement(name = "PodaciODobavljacu", required = true)
    protected TPravnoLice podaciODobavljacu;
    @XmlElement(name = "PodaciOKupcu", required = true)
    protected PodaciOKupcu podaciOKupcu;
    @XmlElement(name = "PodaciRobaIUsluga", required = true)
    protected PodaciRobaIUsluga podaciRobaIUsluga;
    @XmlElement(name = "PodaciOUplati", required = true)
    protected PodaciOUplati podaciOUplati;

    /**
     * Gets the value of the idPoruke property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDPoruke() {
        return idPoruke;
    }

    /**
     * Sets the value of the idPoruke property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDPoruke(String value) {
        this.idPoruke = value;
    }

    /**
     * Gets the value of the podaciODobavljacu property.
     * 
     * @return
     *     possible object is
     *     {@link TPravnoLice }
     *     
     */
    public TPravnoLice getPodaciODobavljacu() {
        return podaciODobavljacu;
    }

    /**
     * Sets the value of the podaciODobavljacu property.
     * 
     * @param value
     *     allowed object is
     *     {@link TPravnoLice }
     *     
     */
    public void setPodaciODobavljacu(TPravnoLice value) {
        this.podaciODobavljacu = value;
    }

    /**
     * Gets the value of the podaciOKupcu property.
     * 
     * @return
     *     possible object is
     *     {@link PodaciOKupcu }
     *     
     */
    public PodaciOKupcu getPodaciOKupcu() {
        return podaciOKupcu;
    }

    /**
     * Sets the value of the podaciOKupcu property.
     * 
     * @param value
     *     allowed object is
     *     {@link PodaciOKupcu }
     *     
     */
    public void setPodaciOKupcu(PodaciOKupcu value) {
        this.podaciOKupcu = value;
    }

    /**
     * Gets the value of the podaciRobaIUsluga property.
     * 
     * @return
     *     possible object is
     *     {@link PodaciRobaIUsluga }
     *     
     */
    public PodaciRobaIUsluga getPodaciRobaIUsluga() {
        return podaciRobaIUsluga;
    }

    /**
     * Sets the value of the podaciRobaIUsluga property.
     * 
     * @param value
     *     allowed object is
     *     {@link PodaciRobaIUsluga }
     *     
     */
    public void setPodaciRobaIUsluga(PodaciRobaIUsluga value) {
        this.podaciRobaIUsluga = value;
    }

    /**
     * Gets the value of the podaciOUplati property.
     * 
     * @return
     *     possible object is
     *     {@link PodaciOUplati }
     *     
     */
    public PodaciOUplati getPodaciOUplati() {
        return podaciOUplati;
    }

    /**
     * Sets the value of the podaciOUplati property.
     * 
     * @param value
     *     allowed object is
     *     {@link PodaciOUplati }
     *     
     */
    public void setPodaciOUplati(PodaciOUplati value) {
        this.podaciOUplati = value;
    }

	@Override
	public String toString() {
		return "Zaglavlje:\n "
				+ "[idPoruke=" + idPoruke + "]\n"
				+ "[podaciODobavljacu=" + podaciODobavljacu.toString() + "]\n"
			    + "[podaciOKupcu=" + podaciOKupcu.toString() + "]\n"
			    + "[podaciRobaIUsluga=" + podaciRobaIUsluga.toString() + "]\n"
			    + "[podaciOUplati=" + podaciOUplati.toString() + "]\n";
	}
	
}
